[workspace]
members = ["programs/*"]

[programs.localnet]
pot_game = "PoTGaMe11111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
